---
- name: Create a cron job
  hosts: vm

  tasks:
    - name: Schedule cron
      cron:
        name: This job is scheduled by Ansible
        minute: "0"
        hour: "10"
        day: "*"
        month: "*"
        weekday: "4"
        user: deployer
        job: "/home/deployer/test/cfile.sh"


# crontab -l