---
- name: Verify apache installation
  hosts: localhost

  tasks:
  - name: Load variables
    include_vars: localhostdetails.txt

  - name: Ensure apache at the latest version
    community.general.homebrew_cask:
      name: httpd
      state: latest
      sudo_password: "{{ local_password }}"

  - name: Copy updated apache config file
    copy:
      src: /tmp/httpd.conf
      dest: /etc/httpd.conf
    notify:
    - Restart apache

  - name: Ensure apache is running
    service:
      name: httpd
      state: started

  handlers:
    - name: Restart apache
      service:
        name: httpd
        state: restarted

# QWERty1234!@
# ansible-playbook handlers.yaml --ask-vault-pass