- name: Create and delete folder on remove server
  hosts: NSO_Servers
  tasks:
    - name: Create Temp directory
      ansible.builtin.tempfile:
        state: directory
        prefix: cisco_bpa
      register: tmp_dir
      
    - name: Display temp variable data
      debug:
        var: "tmp_dir.path"

    - name: copy file to remote directoy
      copy:
        src: Common-Service-CEWA-Voice-Devices2.csv
        dest: "{{tmp_dir.path }}/devices.csv"

    # - name: Use the registered var and the file module to remove the temporary file
    #   ansible.builtin.file:
    #     path: "{{ tmp_dir.path }}"
    #     state: absent
    #   when: tmp_dir.path is defined

